---
output: html_fragment
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Ajax.config.path["mhchem"] =
  "https://cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.2";
MathJax.Hub.Config({
  TeX: {
    extensions: ["[mhchem]/mhchem.js"]
  }
});
MathJax.Hub.Config({ 
        "HTML-CSS": { scale: 90 }, 
        SVG: { linebreaks: { automatic:true } }, 
 });
</script>
```

### Two Problems and Two Solutions

The shiny applications for AC3.0 have a user interface that divides the screen into two columns. The right column is used to display visual elements, such as the image shown here as a placeholder. The left column displays text by passing a `.html file` to `includeHTML()`. The `.html` file was created by knitting a `.Rmd` file using the option `output: html_document`. This approach worked until fall 2023 when warnings showed up in the console noting that `includeHTML()` was provided with a complete HTML document and that this document should be placed, instead, within an iframe. The warning comes from issue [#382](https://github.com/rstudio/htmltools/pull/382), which resolved issue [#124](https://github.com/rstudio/htmltools/issues/124). The change took effect with the release of version 0.5.6 of the `htmltools` package on August 11, 2023. Although the text displayed correctly, the warning is likely to trouble users; thus, the need to fix the code, as noted above, so that a warning does not appear. To solve the problem, `.Rmd` files were knit into `.html` files using option `output: html_fragment`. Using the html fragment introduced a second problem as these files did not include a call to include MathJax; the code at the top of the `.Rmd` files provides for this call. Adding withMathJax() in the `ui.R` file ensures that MathJax is available everywhere. The code at the beginning of each `html` fragment was updated in August 2024 when it was discovered that mhchem was not loading.

### Examples

**Example 1** uses mathjax to format the first mathematical expression and uses Rmarkdown to format the second mathematical expression. **Example 2** uses mhchem to display a chemical formula.

**Example 1**. In order to span a wide range of concentrations, the sliders for concentration are logarithmic; the titrand's default concentration is (*using mathjax*) $10^{-1} = 0.10 \text{ M}$ and the titrant's default concentration is (*using Rmarkdown*) 10^-0.7^ = 0.2 M.

**Example 2**. The monoprotic weak base guanine, (*using mhchem*) $\ce{C5H5N5O}$, is insoluble in water, but fully soluble in acid.
